export const REQUEST_INITIAL_DATA = "request-initial-data"
export const RECOIL_STATE_UPDATE = "recoil-state-update"
export const REQUEST_OPEN_SETTINGS = "request-open-settings"
export const REQUEST_OPEN_PLAYER = "request-open-player"
export const REUQEST_OPEN_WINDOW = "request-open-window"
