/* tslint:disable */
/* eslint-disable */
/**
 * Mirakurun
 * DVR Tuner Server for Japanese TV.
 *
 * The version of the OpenAPI document: 3.9.0-rc.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MirakurunSetting } from "../../types/setting"
import {
  ChannelsApi,
  ConfigApi,
  EventsApi,
  LogApi,
  MiscApi,
  IptvApi,
  ProgramsApi,
  ServicesApi,
  StatusApi,
  StreamApi,
  TunersApi,
  VersionApi,
} from "./api"
import { Configuration } from "./configuration"

export class MirakurunAPI {
  baseUrl: string
  userAgent?: string
  constructor({ baseUrl, userAgent }: Partial<MirakurunSetting>) {
    if (!baseUrl) throw new Error("Mirakurun baseUrl error")
    this.baseUrl = baseUrl
    if (userAgent) {
      this.userAgent = userAgent
    }
  }

  getConfigure() {
    return new Configuration({
      basePath: this.baseUrl,
      userAgent: this.userAgent,
    })
  }

  get channels() {
    return new ChannelsApi(this.getConfigure())
  }

  get config() {
    return new ConfigApi(this.getConfigure())
  }

  get events() {
    return new EventsApi(this.getConfigure())
  }

  get log() {
    return new LogApi(this.getConfigure())
  }

  get misc() {
    return new MiscApi(this.getConfigure())
  }

  get iptv() {
    return new IptvApi(this.getConfigure())
  }

  get programs() {
    return new ProgramsApi(this.getConfigure())
  }

  get services() {
    return new ServicesApi(this.getConfigure())
  }

  get status() {
    return new StatusApi(this.getConfigure())
  }

  get stream() {
    return new StreamApi(this.getConfigure())
  }

  get tuners() {
    return new TunersApi(this.getConfigure())
  }

  get version() {
    return new VersionApi(this.getConfigure())
  }
}
